# примеры API-запросов

# @baseUrl = https://localhost:8000/api
@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/?created_at_after=2024-01-01&created_at_before=2026-12-31
Content-Type: application/json

###

# получение объявлений
GET {{baseUrl}}/advertisements/?status=OPEN
Content-Type: application/json


###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 9cb62c383b69c922bb70fd615666977419952406

{
  "title": "Табурет",
  "description": "Обычный"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/8/
Content-Type: application/json
Authorization: Token 9cb62c383b69c922bb70fd615666977419952406

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2025-10-01
Content-Type: application/json
